# @author: Matteo Caruso
# @email: matteo.caruso@phd.units.it
# @email: matteo.caruso1993@gmail.com

Header header


#CONSTANT
uint8 motors = 8
uint8 firmware_version = 46
uint8 scale_factor = 1

#REST OF THE MESSAGE
uint8 BRWF_Dynamixel_Temperature
uint8 FRWF_Dynamixel_Temperature
uint8 BLWF_Dynamixel_Temperature
uint8 FLWF_Dynamixel_Temperature
uint8 BRWS_Dynamixel_Temperature
uint8 FRWS_Dynamixel_Temperature
uint8 BLWS_Dynamixel_Temperature
uint8 FLWS_Dynamixel_Temperature

