# @author: Matteo Caruso
# @email: matteo.caruso@phd.units.it
# @email: matteo.caruso1993@gmail.com


Header header

#CONSTANT
uint8 motors = 8
uint8 firmware_version = 46
uint8 scale_factor = 1

#REST OF THE MESSAGE

float64 BRWF_Dynamixel_Temperature
float64 FRWF_Dynamixel_Temperature
float64 BLWF_Dynamixel_Temperature
float64 FLWF_Dynamixel_Temperature
float64 BRWS_Dynamixel_Temperature
float64 FRWS_Dynamixel_Temperature
float64 BLWS_Dynamixel_Temperature
float64 FLWS_Dynamixel_Temperature

