# @author: Matteo Caruso
# @email: matteo.caruso@phd.units.it
# @email: matteo.caruso1993@gmail.com

std_msgs/Header header


#CONSTANT
#uint8 MOTORS = 8
#uint8 FIRMWARE_VERSION = 46
#uint8 SCALE_FACTOR = 1

#REST OF THE MESSAGE
uint8 brwf_dynamixel_temperature
uint8 frwf_dynamixel_temperature
uint8 blwf_dynamixel_temperature
uint8 flwf_dynamixel_temperature
uint8 brws_dynamixel_temperature
uint8 frws_dynamixel_temperature
uint8 blws_dynamixel_temperature
uint8 flws_dynamixel_temperature

