# @author: Matteo Caruso
# @email: matteo.caruso@phd.units.it
# @email: matteo.caruso1993@gmail.com

std_msgs/Header header

#CONSTANT
#uint8 MOTORS = 8
#uint8 FIRMWARE_VERSION = 46
#float64 SCALE_FACTOR = 0.2

#REST OF THE MESSAGE


int32 brwf_dynamixel_current
int32 frwf_dynamixel_current
int32 blwf_dynamixel_current
int32 flwf_dynamixel_current
int32 brws_dynamixel_current
int32 frws_dynamixel_current
int32 blws_dynamixel_current
int32 flws_dynamixel_current


